# Postgres
defaults: &defaults
  adapter: postgresql
  host: localhost
  encoding: UTF8
  username: <%= ENV['USERNAME']  %>

development:
  <<: *defaults
  database: cafe_app_dev

# SQLite3
# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# Mysql2
# defaults: &defaults
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: cafe_app_dev
#   pool: 5
#   username: <%= ENV['USERNAME']  %>
#   password: <%= ENV['PASSWORD'] %>
#   socket: /tmp/mysql.sock

# development:
#   <<: *defaults
